#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-andra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-andra
  template:
    metadata:
      labels:
        app: prod-stedi-andra
    spec:
      containers:
        - name: prod-stedi-andra
          image: us-docker.pkg.dev/unstable-unicorns-389016/andra-api/stedi-api:latest
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-andra
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-andra"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: andra-twilio-dev
                  key: twilio_token
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-andra-nodeport
spec:
  selector:
    app: prod-stedi-andra
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-andra-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-andra-public
    networking.gke.io/managed-certificates: prod-stedi-andra-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-andra-nodeport
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-andra-certificate
spec:
  domains:
    - andra.cit262.com
    
